name: Deploy to preview
on:  pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20 # auto create a comment in your PR with preview url
        id: now-deployment
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
      - name: preview-url
        run: |
          # you can see this URL in github action log
          echo ${{ steps.now-deployment.outputs.preview-url }}